name: Java CI

on: push

#on:
#  release:
#    types:
#      - published

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        working-directory: my-app
        run: |
          mvn --batch-mode --update-snapshots package
#          mvn --batch-mode deploy -DaltDeploymentRepository=snapshot-repo::default::file:..
#      - uses: EndBug/add-and-commit@v9
#        with:
#          remove: '-r -f .github my-app README.md'
#          add: './com'
#          new_branch: public
#          push: origin public --set-upstream --force
      - name: Publish package
        working-directory: my-app
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
